version: '3.5'

services:
    frontend:
        ports:
            - 5000:5000
        build: frontend
        depends_on:
            - backend
    backend:
        ports:
            - 8000:8000
        build: backend
        volumes:
            - ./logs.txt:/backend-example-docker/logs.txt
