version: '3.5'

services:
  frontend:
    ports:
      - 5000:5000
    build: ../../Part1/ex110
  backend:
    ports:
      - 8000:8000
    build: ../../Part1/ex111
    volumes: 
      - ./logs.txt:/backend-example-docker/logs.txt
    environment:
      - REDIS=redis 
      - REDIS_PORT=6379
      - DB_USERNAME=anhtumai
      - DB_PASSWORD=password
      - DB_HOST=database
    depends_on:
      - database
    
  redis:
    image: redis
    ports:
      - 6379:6379
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=anhtumai